name: ebuber
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  uberclone:
    path: C:\Users\Salih\Desktop\Flutter\tosbaadriver


  rename: ^2.1.1
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.1
  folding_cell: ^1.0.2
  pinput: ^2.2.31
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_messaging: ^14.0.1
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.0.1
  firebase_storage: ^11.0.1
  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.3.1
  flutter_polyline_points: ^1.0.0
  location: ^5.0.0
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  photo_view: ^0.14.0
  email_auth: ^1.0.0
  dio: ^5.3.2
  flutter_google_places: ^0.3.0
  geolocator: ^9.0.1
  geocoding: ^2.1.0
  http: ^0.13.1
  path_provider: ^2.0.11
  flutter_cache_manager: ^3.3.0
  flutter_rating_bar: ^4.0.1
  permission_handler: ^10.4.3
  flutter_local_notifications: ^15.1.0+1
  url_launcher: ^6.1.12
  flutter_email_sender: ^5.2.0
  change_app_package_name: ^1.1.0
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.6
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  flutter_map_marker_cluster: ^1.1.0
  floating_action_bubble: ^1.1.4
  flutter_expandable_fab: ^2.0.0
  calendar_date_picker2: ^0.5.2
  custom_map_markers: ^0.0.2+1
  screenshot: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  iyzico: ^0.1.1+3
  crypto: ^3.0.3
  encrypt: ^5.0.1
  flutter_credit_card: ^3.0.7
  credit_card_type_detector: ^3.0.0

  #agora_rtc_engine: ^5.3.1
  #agora_uikit: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.0
  flutter_lints: ^2.0.0


flutter_native_splash:
  #color: "#9ED2C3"
  image: "images/app/logo.jpg"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app/logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - images/icons/
    - images/
    - images/ills/
    - images/app/

  fonts:
    - family: Roboto_Condensed
      fonts:
        - asset: fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway/static/Raleway-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
